# Generated by Django 4.2.16 on 2024-12-05 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('GF', 'Gluten Free'), ('QM', '20mins or less'), ('Vg', 'Vegan'), ('V', 'Vegetarian')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='servings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='timings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(blank=True, choices=[('grams', 'Grams'), ('kilograms', 'Kilograms'), ('cups', 'Cups'), ('tablespoon', 'Tablespoon'), ('teaspoon', 'Teaspoon'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='grams', max_length=20, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='blog.post')),
            ],
        ),
    ]
